# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb:10.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_PASSWORD: 123
      MYSQL_USER: root
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 123